FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install -y libopal-dev 
RUN apt-get install -y libpt-dev 
RUN apt-get install -y sip-dev 
RUN apt-get install -y curl 

RUN apt-get update

RUN apt-get install -y telnet
RUN apt-get install -y net-tools
